@startuml
mainframe PasswordValidator validatePassword(String password)

    loop patterns.length() times
        [-> Pattern:compile(pattern)
        activate Pattern
        return compiledPattern
        [-> Pattern:compiledPattern.matcher(password)
        activate Pattern
        return matcher
        [-> Matcher:matches()
        activate Matcher
        alt pattern doesn't match

        return false

        end


    end


@enduml
